name: cc_default
channels:
  - conda-forge
dependencies:
  #############################################
  # System & Environment
  #############################################
  - pandas
  - seaborn
  - scikit-learn
  - imbalanced-learn
  - ipykernel